name: "dynamic jobs test"

on:
  push:
    branches: [ main ]

jobs:
  run_test:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.run_test.outputs.test_result }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      
      - name: Run test
        id: run_test
        run: |
          pytest > test_output.txt  # Save test output to a file
          
      - name: Save Output
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test_output.txt  # Path to the file to upload
