name: "dynamic jobs test"

on:
  push:
    branches: [ main ]

jobs:
  run_test:
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.run_test.outputs.test_result }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      
      - name: Run test
        id: run_test
        run: |
          pytest
          echo "::set-output name=test_result::${PWD}/test_result.json"

  generate_matrix:
    needs: run_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_1_result: [ ${{fromJson(needs.run_test.outputs.test_result)}} ]
    steps:
      - name: Generate Matrix
        run: |
          echo "Using test result: ${{ matrix.job_1_result }}"
