name: Parallel Test Execution

on:
  push:
    branches: [main]

jobs:
  generate-test-batches:
    runs-on: ubuntu-latest
    outputs:
      test_batches: ${{ steps.set-test-batches.outputs.test_batches }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate test batches
        id: set-test-batches
        run: |
          # Execute the script and capture its output
          TEST_BATCHES=$(python batches.py | jq -c .)
          echo "test_batches=$TEST_BATCHES" >> $GITHUB_ENV

  run-tests-parallel:
    needs: generate-test-batches
    strategy:
      matrix:
        test_batch: ${{ fromJson(needs.generate-test-batches.outputs.test_batches) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install
          python -m pip install pytest

      - name: Run tests in parallel
        run: |
          pytest "${{ matrix.test_batch }}"